### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by zhanghua7099** [FangGet/BundleFusion_Ubuntu_Pangolin#1]
Hi!
I have built this project successfully. When I run it, sometimes it goes well. But it may output segmentation fault after processing about 200 frames. The error message is that:
`terminate called after throwing an instance of 'ml::MLibException'
  what():  copyCacheFrameFrom:26: invalid argument:copyCacheFrameFrom
`
`Segmentation fault (core dumped)`
How to fix this bug?

**Comment by zhanghua7099** [comment]
The non-GUI version is OK, but the GUI version may have this problem.

**Comment by FangGet** [comment]
sorry for late reply, I will check this later.

**Comment by FangGet** [comment]
@zhanghua7099 I double checked my code and found no issues related to your problem, I guess its due to gpu memory, please check gpu memory usage when segmentation fault occurs.

**Comment by zhanghua7099** [comment]
GPU memory causes this error. I rerun this code in RTX 2080TI GPU, and it performs well.

**Comment by zhanxiaopan** [comment]
> @zhanghua7099 I double checked my code and found no issues related to your problem, I guess its due to gpu memory, please check gpu memory usage when segmentation fault occurs.

@FangGet Thanks for your great work, I have meet the same issue with @zhanghua7099. However, my GPU is RTX3090(24GB RAM), the segmentation fault occurs after processing 1830 frames（1.21Million triangles）.  It seems reasonable, but how can we iterator the whole 3499 frames for **office2** dataset?
#1: Disable the gui?
#2: Modify some  parameters to reduce the GPU memory?

**Comment by FangGet** [comment]
@zhanxiaopan the real-time visualization needs to ray-trace the whole scenes to output what Pangolin need, and I did this part use GPU, that's why the memory occupancy keeps increasing. By 1) disable the gui, or 2) increase the voxel size, or 3) enable the streaming mode(which only shows the sphere range of scenes) or 4)change the visualization to cpu may help(which may not be real-time).
