### ISSUE TITLE
Hello ! Thanks yours job! Did you use a RGB-D sensor (like Kinect v2 , Structure Sensor or Intel realsensor) to realize BundleFusion in ubuntu?

### ISSUE THREAD

**Issue by luodamao** [FangGet/BundleFusion_Ubuntu_Pangolin#10]

**Comment by FangGet** [comment]
I tried Intel RealSense D435 and other realsense series.
for KinectV2, refer to: [https://github.com/AlDCheng/BundleFusion_Ubuntu_Pangolin](https://github.com/AlDCheng/BundleFusion_Ubuntu_Pangolin)

**Comment by luodamao** [comment]
> I tried Intel RealSense D435 and other realsense series.
> for KinectV2, refer to: https://github.com/AlDCheng/BundleFusion_Ubuntu_Pangolin

Thank you! I'll trt it!

**Comment by DormouseLi** [comment]
Thanks for your  excellent work! How to work with RealSense like D435 or D435i ？ Is there any suggestion?
