### ISSUE TITLE
Hi! Can I use it as a interface(just like Elasticfusion) to do something else? like 3D Semantic Reconstruct.

### ISSUE THREAD

**Issue by luodamao** [FangGet/BundleFusion_Ubuntu_Pangolin#12]
And I wanna know how  to save the Trajetory data like TUM? 

I've found this function: 
void StopScanningAndExit ( bool aborted = false )

In this function, I saw the "write trajectory"
{         //write trajectory
        const std::string saveFile = GlobalAppState::get().s_binaryDumpSensorFile;
        std::vector<mat4f> trajectory;
        g_bundler->getTrajectoryManager()->getOptimizedTransforms ( trajectory );
        numValidTransforms = PoseHelper::countNumValidTransforms ( trajectory );
        numTransforms = ( unsigned int ) trajectory.size();
        if ( numValidTransforms < ( unsigned int ) std::round ( 0.5f * numTransforms ) ) valid = false; // not enough valid transforms
        std::cout << "#VALID TRANSFORMS = " << numValidTransforms << std::endl;
        ( ( SensorDataReader* ) g_RGBDSensor )->saveToFile ( GlobalAppState::get().s_binaryDumpSensorFile + "sequence.sens", trajectory ); //overwrite the original file
}

So I just put the " ( ( SensorDataReader* ) g_RGBDSensor )->saveToFile ( GlobalAppState::get().s_binaryDumpSensorFile + "sequence.sens", trajectory ); //overwrite the original file" in BundleFusion.cpp . In line 368. The project just run one frame.

I really hope you can give me some suggestions!

**Comment by ph-code-repo** [comment]
@luodamao Did you get this working, would be interested to know how you got it to output the trajectory too.
