### ISSUE TITLE
The early reconstructed parts of the scene keep disappearing

### ISSUE THREAD

**Issue by RRRaymond** [FangGet/BundleFusion_Ubuntu_Pangolin#13]
When I use this code to run my own data, as new parts are reconstructed, the earlier reconstructed parts of the scene keep disappearing. The final reconstructed scene is only a small part of the whole scene.
Is this caused by the code, my own data, or the parameter setting? How can I solve this problem?
Looking forward to your reply, thank you very much!

**Comment by FangGet** [comment]
turn off the "streaming" mode in parameter setting.

**Comment by RRRaymond** [comment]
> turn off the "streaming" mode in parameter setting.

Hi, FangGet
Do you mean the **s_streamingEnabled** parameter on [line 100](https://github.com/FangGet/BundleFusion_Ubuntu_Pangolin/blob/master/zParametersDefault.txt#L100) in zParametersDefault.txt? 
This parameter is **false** by default, and I haven't modified it. In addition, after I turned it to **true**, there was no visible change. The early reconstructed parts of the scene still keep disappearing.

**Comment by FangGet** [comment]
yes.
if s_streamingEnabled is set to false, then it's strange for the disappearing. I guess there may be something related to your GPU caused it.
