### ISSUE TITLE
stuck in bundlefusion for cuda 10.0

### ISSUE THREAD

**Issue by Yuanzhuangz** [FangGet/BundleFusion_Ubuntu_Pangolin#15]
`pCallbackFrameRender( pd3dDevice, pd3dImmediateContext, fTime, fElapsedTime, GetDXUTState().GetD3D11FrameRenderFuncUserContext() );`

My program is stuck at the code in DXUT.cpp with windows10+cuda10+2080Ti and other said it is due to the high version of cuda.Since you have successed in migrating the bundlefusion from cuda 8.0 intn cuda 10.0 in Linux,i will appreciate it if you can tell me how to fix the problem.

**Comment by FangGet** [comment]
the render  style for linux is not related to DX on windows, so I have no idea how to solve it.
