### ISSUE TITLE
can't show mesh, how can resolve it?

### ISSUE THREAD

**Issue by jcyhcs** [FangGet/BundleFusion_Ubuntu_Pangolin#16]
hi,professor:
i use your code in jetson nano, compile and run all ok!, but the window can't show mesh, how can i resolve it? PLASE HELP ME!

**Comment by FangGet** [comment]
Hi, jcyhcs:
    I encountered this problem when deploying it on TX2 a long time ago, it seems that the GPU copy process is conflicted with TX2. I just can not remember how to solve it, sorry.
    You can first try compile it with visualization set to OFF.
    BTW, I'm just a CV engineer.
