### ISSUE TITLE
The result is symmetrical

### ISSUE THREAD

**Issue by DormouseLi** [FangGet/BundleFusion_Ubuntu_Pangolin#19]
Hi,Professor.
Thanks for your excellent work!
But it seems that the result is symmetrical to the groud truth. How to fix it ?
By the way, is there any idea to improve the performance?
![Screenshot from 2022-05-06 15-40-07](https://user-images.githubusercontent.com/25239952/167233485-b71cf79c-f080-4c59-b43b-306bcefcae9e.png)
![Screenshot from 2022-05-07 09-45-36](https://user-images.githubusercontent.com/25239952/167233489-ed36d809-14a8-4c19-9ae7-4527db04475e.png)

**Comment by Diana-Zeng** [comment]
Hi！Could you please help me with my error in processing? It is：error: ‘struct pangolin::GlBufferCudaPtr’ has no member named  ‘Free’  vertex_array_global->Free();
and I don't know if it is ralated to the version of Pangolin. Did you meet the same question before? Or is there any advice about it? Thanks a lot.
