### ISSUE TITLE
Failed to save mesh

### ISSUE THREAD

**Issue by bryce-wang-315** [FangGet/BundleFusion_Ubuntu_Pangolin#2]
After I finished all the images data, then I clik the "saveMesh" button on the pangolin window, but I encounter the follow problem " [1] + Done                       "/usr/bin/gdb" --interpreter=mi --tty=${DbgTerm} 0<"/tmp/Microsoft-MIEngine-In-knhbzn1w.k1l" 1>"/tmp/Microsoft-MIEngine-Out-52ts0jac.tk7" ". I don't know why, even though I test the official dataset, I would face this problem. Is there anybody who faced the same problem with me? If you did, please give me some suggestions.

**Comment by bryce-wang-315** [comment]
if I operate it from terminal, I will get the "Segmentation fault (core dumped)" error

**Comment by FangGet** [comment]
I will check that

**Comment by FangGet** [comment]
@bryce-wang-315 For my experience, "Segmentation fault" always relate to gpu memory lack.
For save mesh function, please give a screenshot for your terminal output.

**Comment by bryce-wang-315** [comment]
Thank you very much, I have solved this problem, and I found that the reason is that mybe we have different g++ version. I changed this function bellow.  I changed the second level "for circle", and then it works.
template <class FloatType>
unsigned int MeshData<FloatType>::removeDegeneratedFaces()
{
	Indices newFacesIndicesVertices;
	for (size_t i = 0; i < m_FaceIndicesVertices.size(); i++) {
		std::unordered_set<unsigned int> _set(m_FaceIndicesVertices[i].size());
		bool foundDuplicate = false;
		// for (auto idx : m_FaceIndicesVertices[i]) {
		for (int j = 0; j < m_FaceIndicesVertices[i].size(); ++j) {
 
			auto idx = m_FaceIndicesVertices[i][j];
			if (_set.find(idx) != _set.end()) {
				foundDuplicate = true;
				break;
			} else {
				_set.insert(idx);
			}
		}
 
		if (!foundDuplicate) {
			newFacesIndicesVertices.push_back(m_FaceIndicesVertices[i]);
		}
	}
	if (m_FaceIndicesVertices.size() != newFacesIndicesVertices.size()) {
		m_FaceIndicesVertices = newFacesIndicesVertices;
	}
 
	return (unsigned int)m_FaceIndicesVertices.size();
}

**Comment by FangGet** [comment]
glad to hear that.

**Comment by Uncle-Justice** [comment]
I didn't got this error but when i opened the mesh model in meshlab, it throws a warning about degenerated faces. I followed the code changes above and got no meshlab's warnings any more. Also, I found some colored noise in some border disappeared.
