### ISSUE TITLE
编译时报错

### ISSUE THREAD

**Issue by Diana-Zeng** [FangGet/BundleFusion_Ubuntu_Pangolin#22]
error: ‘struct pangolin::GlBufferCudaPtr’ has no member named ‘Free’
 vertex_array_global->Free();
这个报错不知道是否和Pangolin的版本相关，请问您的pangolin用的是哪个版本的呢？或者您知道该如何解决这个问题吗？

**Comment by guess-who-ami** [comment]
我用Realease 0.6成功了

**Comment by FangGet** [comment]
Sorry for the late reply, we now add docker support for easy usage, please try compiling with the docker environment.
