### ISSUE TITLE
Error during compiling

### ISSUE THREAD

**Issue by sanbuddhacharyas** [FangGet/BundleFusion_Ubuntu_Pangolin#23]
compilation terminated.
CMake Error at BundleFusion_generated_SolverBundling.cu.o.Release.cmake:216 (message):
  Error generating
  /home/predator/Desktop/3D_reconstruction/BundleFusion_Ubuntu_Pangolin/build/CMakeFiles/BundleFusion.dir/src/Solver/./BundleFusion_generated_SolverBundling.cu.o

make[2]: *** [CMakeFiles/BundleFusion.dir/build.make:2514: CMakeFiles/BundleFusion.dir/src/Solver/BundleFusion_generated_SolverBundling.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....

**Comment by FangGet** [comment]
Sorry for the late reply, we now add docker support for easy usage, please try compiling with the docker environment.
