### ISSUE TITLE
make -j8 FAIL 

### ISSUE THREAD

**Issue by Flee-postgra** [FangGet/BundleFusion_Ubuntu_Pangolin#27]
In member function ‘void float4x4::print() const’:
/home/wxh/software/BundleFusion_Ubuntu_Pangolin/include/SiftGPU/cuda_SimpleMatrixUtil.h:1199:305: warning: too many arguments for format [-Wformat-extra-args]
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/BundleFusion.dir/all' failed
make[1]: *** [CMakeFiles/BundleFusion.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

pls ,i have this problem, how to solve it?

**Comment by Flee-postgra** [comment]
if              cmake -DVISUALIZATION=ON ..                      fail 
but         cmake -DVISUALIZATION=OFF ..            pass

when i pass this algorithm,how to run it  withot offline bag ,on my rgbd cam online?
pls!thanks~

**Comment by FangGet** [comment]
Sorry for the late reply, we now add docker support for easy usage, please try compiling with the docker environment.
