### ISSUE TITLE
why there is not PangolinOutputWrapper.h?

### ISSUE THREAD

**Issue by zhuangpeixi** [FangGet/BundleFusion_Ubuntu_Pangolin#3]
fatal error: PangolinOutputWrapper.h: 没有那个文件或目录
 #include <PangolinOutputWrapper.h>

**Comment by FangGet** [comment]
locate in https://github.com/FangGet/BundleFusion_Ubuntu_Pangolin/blob/d3390f9017ddcdf31c69d65155ef356c4a5b2dd6/include/Visualization/PangolinOutputWrapper.h, check you cmake version or just change the #include path

**Comment by zhuangpeixi** [comment]
> locate in https://github.com/FangGet/BundleFusion_Ubuntu_Pangolin/blob/d3390f9017ddcdf31c69d65155ef356c4a5b2dd6/include/Visualization/PangolinOutputWrapper.h, check you cmake version or just change the #include path

**Comment by zhuangpeixi** [comment]
thanks.
