### ISSUE TITLE
能运行,但是不能实时显示和保存Mesh

### ISSUE THREAD

**Issue by Thomson617** [FangGet/BundleFusion_Ubuntu_Pangolin#6]
我在Ubuntu16.0.4上跑通,一切都没问题(实时显示与保存),
但在TX2板(也是Ubuntu16.0.4系统)上跑遇到故障:
不能实时显示Mesh,也不能保存Mesh,输出信息中Triangle Size为0。(轨迹与camera的显示都没问题,编译过程也没问题)
困扰了好几天,有知道问题所在的吗?
![微信图片_20201026172407](https://user-images.githubusercontent.com/41614362/97155383-3ffa8e00-17b0-11eb-9d82-35ed58faffb8.jpg)

**Comment by FangGet** [comment]
TX2 has some problem with pangolin gpu operation, I encountered this phenomenon before and fixed it up, but I forgot how to right now, it seems to be some CUDA coding. I will check for past log file.

**Comment by shunliuniliu** [comment]
请问是怎样解决这个问题的？

**Comment by apperrs** [comment]
请问是如何解决的，现在也碰到一模一样的问题

**Comment by Leerw** [comment]
@Thomson617 @FangGet @apperrs Does any solution available? I encountered the same issue.

**Comment by pandahops1** [comment]
cmake的时候他readme里面有个选项，可以设置成on，再装个pangolin就可以运行实时的

**Comment by 77waiwai-Demon** [comment]
![image](https://user-images.githubusercontent.com/62922716/216646373-c16389c4-7525-449d-b2ad-0311594f4a02.png)
为什么我z只有rgb_image这一个窗口，重建过程没有
