### ISSUE TITLE
How to make a mesh model as large as BundleFusion's official dataset？

### ISSUE THREAD

**Issue by Uncle-Justice** [FangGet/BundleFusion_Ubuntu_Pangolin#8]
Hi, I wonder if you have also noticed that the mesh data in BundleFusion's official dataset are like six times larger than those generated by your code. For example, the size of  ```office2.ply``` in ```https://graphics.stanford.edu/projects/bundlefusion/``` is 300MB while the size of ```office2.ply``` you offered in google drive is 50MB. 

In the aspect of visualization, the code is good enough to use. But I got some trouble in ```https://github.com/chaowang15/plane-opt-rgbd```. Only when i used the official mesh model can i got the correct result.

In addition, I tried this in Win10's BundleFusion(official code) and got 50MB `office2.ply``` too. So i just want to discuss the situation with you. 

Hope you'll offer me some new ideas, thanks.

**Comment by FangGet** [comment]
A down sample strategy for depth image integration is adopted in this project，and other parameters setting changes are also applied, to make it run on single GPU in real time. This may be the causes for model size decrease. Btw, voxel size may also matters.
