### ISSUE TITLE
Failed to build !! 

### ISSUE THREAD

**Issue by wk738126046** [FangGet/BundleFusion_Ubuntu_Pangolin#9]
Hi, thanks for the great job.
I can't build successfully like this:
         
_In file included from /home/**/BundleFusion/include/mLib/include/mLibCore.h:150:0,
                 from /home/**/BundleFusion/include/mLib.h:7,
                 from /home/**BundleFusion/include/stdafx.h:2,
                 from /home/**/BundleFusion/src/Bundler.cpp:1:
/usr/local/include/opencv2/viz/types.hpp: At global scope:
/home/**/BundleFusion/include/mLib/include/core-util/keycodes.h:22:31: error: **expected identifier before numeric constant**
 #define KEY_UP                38
/home/**/BundleFusion/include/mLib/include/core-util/keycodes.h:22:31: error: expected ‘}’ before numeric constant
/home/**/BundleFusion/include/mLib/include/core-util/keycodes.h:22:31: error: expected unqualified-id before numeric constant
In file included from /usr/local/include/opencv2/viz.hpp:49:0,
                 from /usr/local/include/opencv2/opencv.hpp:104,
                 from /home/**/BundleFusion/include/RGBDSensor.h:7,
                 from /home/**/BundleFusion/include/CUDAImageManager.h:2,
                 from /home/**/BundleFusion/src/Bundler.cpp:7:
/usr/local/include/opencv2/viz/types.hpp:295:34: error: expected ‘)’ before ‘action’
             KeyboardEvent(Action action, const String& symbol, unsigned char code, int modifiers);
/usr/local/include/opencv2/viz/types.hpp:297:13: error: ‘Action’ does not name a type; did you mean ‘ctime’?
             Action action;
             ctime
/usr/local/include/opencv2/viz/types.hpp:331:1: error: expected declaration before ‘}’ token
 } /* namespace cv */_
----------------------
the environment is ubuntu16/GCC7 /opencv3.4/CUDA10.1.
please how to fix it ?? thanks a lot.

**Comment by FangGet** [comment]
never came up with this problem, it seems relates to opencv viz problem.
my compile env is showed at the screenshot:
![image](https://user-images.githubusercontent.com/11433213/104540658-dc6b5880-565a-11eb-87cf-db23359dcc3d.png)

**Comment by jcyhcs** [comment]
@wk738126046  
i also got this problem, how can you resolve it? please tell me! thx

**Comment by ph-code-repo** [comment]
I had this problem using opencv 4.5.2 (ubuntu 18.04/gcc 7.5/CUDA 11.4)
@wk738126046 @jcyhcs - any luck resolving the issue?

**Comment by ph-code-repo** [comment]
@jcyhcs ensuring you have opencv4.3.0 or higher worked for me. I also had to enforce gcc version 6 to compile the CUDA functions properly.
